### ISSUE TITLE
Need get report method by job ID and hash

### ISSUE THREAD

**Issue by zuberc-cds** [passimens/atdlib#1]
There are 2 methods required for the following APIs:

https://<MATD_IP>/php/showreport.php?jobId=10&iType=json
https://<MATD_IP>/php/showreport.php?md5=E2CFE1C89703352C42763E4B458FC356&iType=html

**Comment by passimens** [comment]
Thanks for your feedback. I'll review these after the NY holidays. At the time I initially created the library, showreport for jobId didn't return anything more than what jobstatus returns.
MD5 report makes sense. API guide does not definitely says what is returned for this type of query. I believe it should be the same as for iTaskId = "latest task with the respective hash value".
